var x = 5;
var y = 10;
console.log("Is x < y? I predict True.");
console.log(x < y);
console.log("Is y > x? I predict True.");
console.log(y > x);
console.log("Is x == 5? I predict True.");
console.log(x == 5);
console.log("Is x != y? I predict True.");
console.log(x != y);
console.log("Is y <= 10? I predict True.");
console.log(y <= 10);
console.log("Is x > 10? I predict False.");
console.log(x > 10);
console.log("Is y == 5? I predict False.");
console.log(y == 5);
console.log("Is x > y? I predict False.");
console.log(x > y);
console.log("Is y < 5? I predict False.");
console.log(y < 5);
console.log("Is x == y? I predict False.");
console.log(x == y);
